### ISSUE TITLE
About Eval Results

### ISSUE THREAD

**Issue by YaoShangJing** [gswycf/SignGraph#10]
Hi!Your CVPR work is simply amazing, our team is very interested in it. We have some questions we would like to ask you.

1、We noticed that the weight evaluation results updated in your code repository are much better than those reported in the paper. We also reproduced the experiments on the A1000, but the experimental results are as follows:
![image](https://github.com/user-attachments/assets/0cd102bf-35dd-4584-b64d-e8f43d7b7749)
Could you please let us know if it's because the new training config file was not updated, or if you used any special tricks during the training process?

2、Does your code support multi-GPU training? I saw some related code implementation, but I tried some training commands and they were not successful.

**Comment by gswycf** [comment]
Hi, thanks for your attention. 

 Evaluation results updated in your code repository are much better than those reported in the paper? See readme.md "We make some imporvments of our code, and provide newest checkpoionts and better performance."

About your  experimental results, have you ever modify the config file? or try to retrain the model agagin?  The initial Graph building is random, and different platforms may cause different initializations, which in turn affects the subsequent training process.

Multi-GPU training? Theoretically, the code supports multi-gpu training, but I found that the batch parameters under multi-gpu may need to be adjusted appropriately to achieve the best performance, so I chose a single-gpu model. Can you post the error message of your multi GPU training?

**Comment by YaoShangJing** [comment]
I'm sorry for the impertinent questions due to my carelessness. You've already provided very good answers to my questions. I will try retraining on another device. Thank you very much for your responses.

**Comment by gswycf** [comment]
> I'm sorry for the impertinent questions due to my carelessness. You've already provided very good answers to my questions. I will try retraining on another device. Thank you very much for your responses.

It is not a the impertinent question. About reproducibility , i have tried to adopte "[torch.use_deterministic_algorithms()](https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms)" but current code is incompatible with this command. Sometimes, i can not get same results without change anything. What I can guarantee is that the weights of the model above were indeed trained using the  current code.
