### ISSUE TITLE
CSL数据集不能用了吗？

### ISSUE THREAD

**Issue by yangw8** [gswycf/SignGraph#12]
下载了两个数据集不能压缩，这是怎么回事

**Comment by gswycf** [comment]
Hi, you may contact thedataset  publisher  to ask about it.

**Comment by yangw8** [comment]
你好，请问你也是来学习的吗，我要怎么联系他啊，感觉像是大海捞针一样

**Comment by gswycf** [comment]
Send a email, maybe
