### ISSUE TITLE
What improvements of the code?

### ISSUE THREAD

**Issue by yuyiheng-eu** [gswycf/SignGraph#15]
Hello, this is a great job. However, we noticed that the performance of the provided code is significantly better than what is reported in the paper. Could you please specify what improvements were made?

**Comment by gswycf** [comment]
Hi, Thank you for your attention to our work. We change the liner layer to conv layer in sign graph module, and retrained our model based on previous checkpoints, which leads to a better performance.

**Comment by yuyiheng-eu** [comment]
Thank you very much for your prompt reply. I would like to know why changing the linear layer to conv layer can improve performance. Is there any explanation behind this?

**Comment by gswycf** [comment]
Hi, I can't really give this a good explanation. Sorry for that. One more thing that i noticed that  if you retrained model based on previous checkpoints, the results can be better.
