### ISSUE TITLE
[Request] Training Log

### ISSUE THREAD

**Issue by imkzh** [gswycf/SignGraph#16]
Can we have the training log for the pre-trained models? The log file provides insights for the optimization process, so that we can inspect/compare our model training process. Thanks in advance.

**Comment by gswycf** [comment]
[log.txt](https://github.com/user-attachments/files/17929383/log.txt)
Sure, Here is one of our training log for Phoenix14T. Thanks for your attentions.

**Comment by imkzh** [comment]
Wow, thank you for your timely reply, currently I'm working on `CSL-Daily`-specific optimizations, can I have the log for the `CSL-Daily` model?

**Comment by gswycf** [comment]
I just searched my server and some work_dirs were deleted by me due to insufficient disk space. I can't find the work_dir of CSL_Daily for this project. I'm sorry about that. Thanks again for your attentions.

**Comment by imkzh** [comment]
Thanks again for your work and code, I'm closing this issue as resolved.

**Comment by DingDSJ** [comment]
Thank you for sharing the training log. I noticed that the initial WER in log.txt is already 20.81, while the parameters 'load_weights': False and 'load_checkpoints': False are set. Could you please clarify if any pre-trained weights were used during training? If so, would it be possible to share these weights?

Thank you very much for your time and support!
