### ISSUE TITLE
IndexError: list index out of range!

### ISSUE THREAD

**Issue by muxiddin19** [gswycf/SignGraph#4]
There is another issue while I start the training code:
(signgraph) wsl@DESKTOP-CJL0ECN:/mnt/h/muhiddin/signgraph$ python main.py --device 1
Not using distributed mode
[0]
Loading model
learning rate conv2d=0.0001
learning rate conv1d=0.0001
learning rate temporal_model=0.0001
learning rate classifier=0.0001
Loading model finished.
Loading Dataprocessing
train 7096
Apply training transform.

train 7096
Apply testing transform.

dev 519
Apply testing transform.

test 642
Apply testing transform.

Loading Dataprocessing finished.
Working tree is dirty. Patch:
diff --git a/configs/baseline.yaml b/configs/baseline.yaml
index bfc1da8..19c50ba 100644
--- a/configs/baseline.yaml
+++ b/configs/baseline.yaml
@@ -1,8 +1,9 @@
 feeder: dataset.dataloader_video.BaseFeeder
 phase: train
+#dataset: phoenix2014
 dataset: phoenix2014-T
 #CSL-Daily
-# dataset: phoenix14-si5
+#dataset: phoenix14-si5

 work_dir: ./work_dirt/
 batch_size: 4
diff --git a/configs/phoenix2014-T.yaml b/configs/phoenix2014-T.yaml
index 52d91a6..7f5adb8 100644
--- a/configs/phoenix2014-T.yaml
+++ b/configs/phoenix2014-T.yaml
@@ -1,4 +1,5 @@
-dataset_root: "/data/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/"
+dataset_root: ./PHOENIX-2014-T-release-v3/PHOENIX-2014-T/
+#dataset_root: "./data/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/"

 dict_path: ./preprocess/phoenix2014-T/gloss_dict.npy
 evaluation_dir: ./evaluation/slr_eval
diff --git a/configs/phoenix2014.yaml b/configs/phoenix2014.yaml
index 500b8eb..b031086 100644
--- a/configs/phoenix2014.yaml
+++ b/configs/phoenix2014.yaml
@@ -1,4 +1,4 @@
-dataset_root: /phoenix2014-release/phoenix-2014-multisigner
+dataset_root: ./phoenix2014-release/phoenix-2014-multisigner
 dict_path: ./preprocess/phoenix2014/gloss_dict.npy
 evaluation_dir: ./evaluation/slr_eval
 evaluation_prefix: phoenix2014-groundtruth
diff --git a/dataset/__init__.py b/dataset/__init__.py
index 923ed7e..cea2766 100644
--- a/dataset/__init__.py
+++ b/dataset/__init__.py
@@ -1 +1,2 @@
-from .video_augmentation_torch import *
\ No newline at end of file
+#from .video_augmentation_torch import *
+from .dataloader_video import *
\ No newline at end of file
diff --git a/main.py b/main.py
index 758e7c1..1863110 100644
--- a/main.py
+++ b/main.py
@@ -18,7 +18,8 @@ from collections import OrderedDict

 faulthandler.enable()
 import utils
-from seq_scripts import seq_train, seq_eval, seq_feature_generation
+#from seq_scripts import seq_train, seq_eval, seq_feature_generation
+from seq_scripts import seq_train, seq_eval
 from torch.cuda.amp import autocast as autocast
 from utils.misc import *
 class Processor():

[ Tue Jun 18 12:46:43 2024 ] Parameters:
{'work_dir': './work_dirt/', 'config': './configs/baseline.yaml', 'random_fix': True, 'device': '1', 'phase': 'train', 'save_interval': 10, 'random_seed': 0, 'eval_interval': 1, 'print_log': True, 'log_interval': 10000, 'evaluate_tool': 'python', 'feeder': 'dataset.dataloader_video.BaseFeeder', 'dataset': 'phoenix2014-T', 'dataset_info': {'dataset_root': './PHOENIX-2014-T-release-v3/PHOENIX-2014-T/', 'dict_path': './preprocess/phoenix2014-T/gloss_dict.npy', 'evaluation_dir': './evaluation/slr_eval', 'evaluation_prefix': 'phoenix2014-T-groundtruth'}, 'num_worker': 20, 'feeder_args': {'mode': 'test', 'datatype': 'video', 'num_gloss': -1, 'drop_ratio': 1.0, 'frame_interval': 1, 'image_scale': 1.0, 'input_size': 224, 'prefix': './PHOENIX-2014-T-release-v3/PHOENIX-2014-T/', 'transform_mode': False}, 'model': 'slr_network.SLRModel', 'model_args': {'num_classes': 1116, 'c2d_type': 'resnet18', 'conv_type': 2, 'use_bn': 1, 'share_classifier': True, 'weight_norm': True}, 'load_weights': False, 'load_checkpoints': False, 'decode_mode': 'beam', 'ignore_weights': [], 'batch_size': 4, 'test_batch_size': 4, 'loss_weights': {'SeqCTC': 1.0, 'ConvCTC': 1.0, 'Dist': 25.0}, 'optimizer_args': {'optimizer': 'Adam', 'learning_rate': {}, 'step': [20, 30, 35], 'learning_ratio': 1, 'scheduler': 'ScheaL', 'weight_decay': 0.0001, 'start_epoch': 0, 'num_epoch': 101, 'nesterov': False}, 'num_epoch': 80, 'world_size': 1, 'local_rank': -1, 'dist_url': 'env://'}

/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:139: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:152: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
  0%|                                                                                          | 0/1774 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/h/muhiddin/signgraph/main.py", line 304, in <module>
    processor.start()
  File "/mnt/h/muhiddin/signgraph/main.py", line 69, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "/mnt/h/muhiddin/signgraph/seq_scripts.py", line 26, in seq_train
    for batch_idx, data in enumerate(tqdm(loader)):
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/h/muhiddin/signgraph/dataset/dataloader_video.py", line 51, in __getitem__
    input_data, label = self.normalize(input_data, label)
  File "/mnt/h/muhiddin/signgraph/dataset/dataloader_video.py", line 92, in normalize
    video, label = self.data_aug(video, label, file_id)
  File "/mnt/h/muhiddin/signgraph/utils/video_augmentation.py", line 111, in __call__
    image = t(image)
  File "/mnt/h/muhiddin/signgraph/utils/video_augmentation.py", line 206, in __call__
    if isinstance(clip[0], np.ndarray):
IndexError: list index out of range

Can you please, help me addressing this issue, as could not do it with myself?

**Comment by gswycf** [comment]
hi，do you change your dataset path in config file?

**Comment by muxiddin19** [comment]
Yes, I think I did. Can you please check them?
![image](https://github.com/gswycf/SignGraph/assets/54941476/78dca21e-ad0c-49f4-a736-dc349031e42e)
![image](https://github.com/gswycf/SignGraph/assets/54941476/4c2ac906-edad-4e57-8948-bdce77cf2436)
![image](https://github.com/gswycf/SignGraph/assets/54941476/d0926d18-91d5-49b4-bd70-4eab8a9364c1)

**Comment by gswycf** [comment]
[ Tue Jun 18 12:46:43 2024 ] Parameters:
{'work_dir': './work_dirt/', 'config': './configs/baseline.yaml', 'random_fix': True, 'device': '1', 'phase': 'train', 'save_interval': 10, 'random_seed': 0, 'eval_interval': 1, 'print_log': True, 'log_interval': 10000, 'evaluate_tool': 'python', 'feeder': 'dataset.dataloader_video.BaseFeeder', 'dataset': 'phoenix2014-T', 'dataset_info': {'dataset_root': './PHOENIX-2014-T-release-v3/PHOENIX-2014-T/', 'dict_path': './preprocess/phoenix2014-T/gloss_dict.npy', 'evaluation_dir': './evaluation/slr_eval', 'evaluation_prefix': 'phoenix2014-T-groundtruth'}, 'num_worker': 20, 'feeder_args': {'mode': 'test', 'datatype': 'video', 'num_gloss': -1, 'drop_ratio': 1.0, 'frame_interval': 1, 'image_scale': 1.0, 'input_size': 224, 'prefix': './PHOENIX-2014-T-release-v3/PHOENIX-2014-T/', 'transform_mode': False}, 'model': 'slr_network.SLRModel', 'model_args': {'num_classes': 1116, 'c2d_type': 'resnet18', 'conv_type': 2, 'use_bn': 1, 'share_classifier': True, 'weight_norm': True}, 'load_weights': False, 'load_checkpoints': False, 'decode_mode': 'beam', 'ignore_weights': [], 'batch_size': 4, 'test_batch_size': 4, 'loss_weights': {'SeqCTC': 1.0, 'ConvCTC': 1.0, 'Dist': 25.0}, 'optimizer_args': {'optimizer': 'Adam', 'learning_rate': {}, 'step': [20, 30, 35], 'learning_ratio': 1, 'scheduler': 'ScheaL', 'weight_decay': 0.0001, 'start_epoch': 0, 'num_epoch': 101, 'nesterov': False}, 'num_epoch': 80, 'world_size': 1, 'local_rank': -1, 'dist_url': 'env://'} 

in your log, dataset_root still is './PHOENIX-2014-T-release-v3/PHOENIX-2014-T/' instead of "./data/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/".

**Comment by gswycf** [comment]
> an you please check them?

Does the error still occur after you changed the path?

**Comment by muxiddin19** [comment]
Yes, it does for both Phoenix datasets. CSL dataset is being downloaded, I will try on it later while downloading is done.

**Comment by gswycf** [comment]
hi， can you you show your pheonix dataset : "PHOENIX-2014-T/features', make sure there are folders that contain images.

**Comment by muxiddin19** [comment]
![image](https://github.com/gswycf/SignGraph/assets/54941476/a503740a-6a62-4037-a44f-0ee943c8a595)
![image](https://github.com/gswycf/SignGraph/assets/54941476/0cbee77d-cd68-469e-9b2c-a8b4730c75e5)

**Comment by gswycf** [comment]
hi, you can add "print(image_folder, image_list)" after line71 in dataloader.py for debugging to see if image_folder are right path in your device.

**Comment by muxiddin19** [comment]
(signgraph) wsl@DESKTOP-CJL0ECN:/mnt/h/muhiddin/signgraph$ python main.py --device 0
Not using distributed mode
[0]
Loading model
learning rate conv2d=0.0001
learning rate conv1d=0.0001
learning rate temporal_model=0.0001
learning rate classifier=0.0001
Loading model finished.
Loading Dataprocessing
train 5671
Apply training transform.

train 5671
Apply testing transform.

dev 540
Apply testing transform.

test 629
Apply testing transform.

Loading Dataprocessing finished.
Working tree is dirty. Patch:
diff --git a/configs/baseline.yaml b/configs/baseline.yaml
index bfc1da8..260b46d 100644
--- a/configs/baseline.yaml
+++ b/configs/baseline.yaml
@@ -1,8 +1,9 @@
 feeder: dataset.dataloader_video.BaseFeeder
 phase: train
-dataset: phoenix2014-T
+dataset: phoenix2014
+#dataset: phoenix2014-T
 #CSL-Daily
-# dataset: phoenix14-si5
+#dataset: phoenix14-si5

 work_dir: ./work_dirt/
 batch_size: 4
diff --git a/configs/phoenix2014-T.yaml b/configs/phoenix2014-T.yaml
index 52d91a6..7fa114f 100644
--- a/configs/phoenix2014-T.yaml
+++ b/configs/phoenix2014-T.yaml
@@ -1,4 +1,5 @@
-dataset_root: "/data/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/"
+#dataset_root: ./PHOENIX-2014-T-release-v3/PHOENIX-2014-T/
+dataset_root: "./data/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/"

 dict_path: ./preprocess/phoenix2014-T/gloss_dict.npy
 evaluation_dir: ./evaluation/slr_eval
diff --git a/dataset/__init__.py b/dataset/__init__.py
index 923ed7e..cea2766 100644
--- a/dataset/__init__.py
+++ b/dataset/__init__.py
@@ -1 +1,2 @@
-from .video_augmentation_torch import *
\ No newline at end of file
+#from .video_augmentation_torch import *
+from .dataloader_video import *
\ No newline at end of file
diff --git a/dataset/dataloader_video.py b/dataset/dataloader_video.py
index 555f4b8..dd98729 100644
--- a/dataset/dataloader_video.py
+++ b/dataset/dataloader_video.py
@@ -69,6 +69,7 @@ class BaseFeeder(data.Dataset):
             img_folder = os.path.join(self.prefix, "sentence/frames_512x512/" + fi['folder'])
         img_list = sorted(glob.glob(img_folder))
         img_list = img_list[int(torch.randint(0, self.frame_interval, [1]))::self.frame_interval]
+        print(img_folder, img_list)
         label_list = []
         if self.dataset=='phoenix2014':
             fi['label'] = clean_phoenix_2014(fi['label'])
diff --git a/main.py b/main.py
index 758e7c1..1863110 100644
--- a/main.py
+++ b/main.py
@@ -18,7 +18,8 @@ from collections import OrderedDict

 faulthandler.enable()
 import utils
-from seq_scripts import seq_train, seq_eval, seq_feature_generation
+#from seq_scripts import seq_train, seq_eval, seq_feature_generation
+from seq_scripts import seq_train, seq_eval
 from torch.cuda.amp import autocast as autocast
 from utils.misc import *
 class Processor():

[ Tue Jun 18 18:31:09 2024 ] Parameters:
{'work_dir': './work_dirt/', 'config': './configs/baseline.yaml', 'random_fix': True, 'device': '0', 'phase': 'train', 'save_interval': 10, 'random_seed': 0, 'eval_interval': 1, 'print_log': True, 'log_interval': 10000, 'evaluate_tool': 'python', 'feeder': 'dataset.dataloader_video.BaseFeeder', 'dataset': 'phoenix2014', 'dataset_info': {'dataset_root': '/phoenix2014-release/phoenix-2014-multisigner', 'dict_path': './preprocess/phoenix2014/gloss_dict.npy', 'evaluation_dir': './evaluation/slr_eval', 'evaluation_prefix': 'phoenix2014-groundtruth'}, 'num_worker': 20, 'feeder_args': {'mode': 'test', 'datatype': 'video', 'num_gloss': -1, 'drop_ratio': 1.0, 'frame_interval': 1, 'image_scale': 1.0, 'input_size': 224, 'prefix': '/phoenix2014-release/phoenix-2014-multisigner', 'transform_mode': False}, 'model': 'slr_network.SLRModel', 'model_args': {'num_classes': 1296, 'c2d_type': 'resnet18', 'conv_type': 2, 'use_bn': 1, 'share_classifier': True, 'weight_norm': True}, 'load_weights': False, 'load_checkpoints': False, 'decode_mode': 'beam', 'ignore_weights': [], 'batch_size': 4, 'test_batch_size': 4, 'loss_weights': {'SeqCTC': 1.0, 'ConvCTC': 1.0, 'Dist': 25.0}, 'optimizer_args': {'optimizer': 'Adam', 'learning_rate': {}, 'step': [20, 30, 35], 'learning_ratio': 1, 'scheduler': 'ScheaL', 'weight_decay': 0.0001, 'start_epoch': 0, 'num_epoch': 101, 'nesterov': False}, 'num_epoch': 80, 'world_size': 1, 'local_rank': -1, 'dist_url': 'env://'}

/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:139: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:152: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
  0%|                                                                                          | 0/1417 [00:00<?, ?it/s]/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/22October_2009_Thursday_tagesschau_default-0/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/14June_2010_Monday_heute_default-7/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/27February_2011_Sunday_tagesschau_default-3/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/09June_2010_Wednesday_heute_default-11/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/02November_2010_Tuesday_heute_default-10/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/02February_2011_Wednesday_tagesschau_default-0/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/18September_2010_Saturday_tagesschau_default-4/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/05July_2011_Tuesday_tagesschau_default-2/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/24July_2011_Sunday_tagesschau_default-10/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/08April_2010_Thursday_heute_default-5/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/24July_2010_Saturday_tagesschau_default-10/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/26August_2010_Thursday_tagesschau_default-11/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/16March_2011_Wednesday_tagesschau_default-7/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/12April_2010_Monday_heute_default-4/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/31May_2011_Tuesday_heute_default-23/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/23March_2011_Wednesday_tagesschau_default-10/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/19May_2010_Wednesday_heute_default-9/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/26May_2010_Wednesday_heute_default-5/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/08July_2010_Thursday_tagesschau_default-13/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/29August_2009_Saturday_tagesschau_default-0/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/28September_2010_Tuesday_heute_default-3/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/13April_2011_Wednesday_tagesschau_default-12/1/*.png []
  0%|                                                                                          | 0/1417 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/h/muhiddin/signgraph/main.py", line 304, in <module>
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/08April_2010_Thursday_heute_default-2/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/10January_2010_Sunday_tagesschau_default-10/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/08February_2010_Monday_tagesschau_default-10/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/15December_2009_Tuesday_tagesschau_default-0/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/23May_2011_Monday_tagesschau_default-11/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/04October_2010_Monday_tagesschau_default-15/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/05February_2011_Saturday_tagesschau_default-3/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/05April_2010_Monday_tagesschau_default-11/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/06October_2010_Wednesday_tagesschau_default-8/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/06December_2010_Monday_heute_default-2/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/21November_2009_Saturday_tagesschau_default-2/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/07December_2011_Wednesday_tagesschau_default-8/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/13July_2010_Tuesday_heute_default-4/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/21October_2009_Wednesday_tagesschau_default-0/1/*.png []
    processor.start()
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/30November_2011_Wednesday_tagesschau_default-7/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/10May_2010_Monday_tagesschau_default-2/1/*.png []
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/26April_2010_Monday_tagesschau_default-13/1/*.png []
  File "/mnt/h/muhiddin/signgraph/main.py", line 69, in start
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/09June_2010_Wednesday_tagesschau_default-13/1/*.png []
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "/mnt/h/muhiddin/signgraph/seq_scripts.py", line 26, in seq_train
    for batch_idx, data in enumerate(tqdm(loader)):
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/12November_2009_Thursday_tagesschau_default-2/1/*.png []
    data.reraise()
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/h/muhiddin/signgraph/dataset/dataloader_video.py", line 51, in __getitem__
    input_data, label = self.normalize(input_data, label)
  File "/mnt/h/muhiddin/signgraph/dataset/dataloader_video.py", line 93, in normalize
    video, label = self.data_aug(video, label, file_id)
  File "/mnt/h/muhiddin/signgraph/utils/video_augmentation.py", line 111, in __call__
    image = t(image)
  File "/mnt/h/muhiddin/signgraph/utils/video_augmentation.py", line 206, in __call__
    if isinstance(clip[0], np.ndarray):
IndexError: list index out of range

**Comment by gswycf** [comment]
"/phoenix2014-release/phoenix-2014-multisigner/features/fullFrame-210x260px/train/30November_2011_Wednesday_tagesschau_default-7/1/.png []" 
Here, your data path may be not right, i think, otherwise, "image_list" should not be "[]"

**Comment by muxiddin19** [comment]
Okay, I will check it one more time

**Comment by muxiddin19** [comment]
It was a dataset related issue. I have redownloaded the data and the issue was solved.
