### ISSUE TITLE
Missing of Function

### ISSUE THREAD

**Issue by Dodo-D-Caster** [gswycf/SignGraph#7]
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from seq_scripts import seq_train, seq_eval, seq_feature_generation
ImportError: cannot import name 'seq_feature_generation' from 'seq_scripts'

It seems the `seq_feature_generation` function in `seq_scripts.py` is missing.

**Comment by gswycf** [comment]
Hi, thanks for your noticing, we have updated the main.py and del seq_feature_generation function. It is not used in this project.

**Comment by Dodo-D-Caster** [comment]
thx:)
