### ISSUE TITLE
 No module named 'dataset.video augmentation torch

### ISSUE THREAD

**Issue by jyn1102** [gswycf/SignGraph#9]
<img width="1115" alt="微信图片_20240807191650" src="https://github.com/user-attachments/assets/12dd6a5b-f9b9-4253-9591-41287cec1c50">
How to solve this problem？

**Comment by gswycf** [comment]
Hi, try to del “dataset/__init__.py”. and I already update the __init__.py

**Comment by jyn1102** [comment]
![12](https://github.com/user-attachments/assets/819203f1-dc8f-4714-a7ba-220048d2755d)
我使用了soft link，ln -s PATH_TO_DATASET/phoenix2014-release ./dataset/phoenix2014这样放对吗？
But there are some errors in data processing

**Comment by gswycf** [comment]
Just change the data_path to the actual phoenix2014T path. Or you can post the errors here to see whether it is a path problem？

**Comment by jyn1102** [comment]
Thank you for your response!!!Now I configure the dataset path properly. Now the project is up and running.
